title: Yangee Github Page
github: [metadata]
name: Jihyun Yang
kramdown:
  input: GFM
  hard_wrap: false
gems:
  - jekyll-coffeescript
  - jekyll-paginate
remote_theme: "mmistakes/minimal-mistakes"
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
    path: ""
    type: pages
  values:
    layout: single
    author_profile: true